name = "iron-recruitment"
compatibility_date = "2026-09-01"
pages_build_output_dir = "dist"

# Cloudflare D1 Database Binding
[[d1_databases]]
binding = "DB"
database_name = "iron-db"
database_id = "b943e6ec-265f-464c-8491-0a841b894788"
migrations_dir = "./migrations"

[vars]
JWT_SECRET = "iron_campus_recruitment_jwt_secret_key_2026"
APP_NAME = "IRON"
